extends: airbnb-base
rules:
  brace-style: 0
  class-methods-use-this: 0
  global-require: 0
  import/no-dynamic-require: 0
  import/order: 0
  max-len: 0
  newline-per-chained-call: 0
  no-console: 0
  no-restricted-syntax: 0
  no-underscore-dangle: 0
  prefer-destructuring: 0
